name: Push to Staging

on:
  push:
    branches:
      - main

jobs:
  push-to-staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      # Pull latest changes from the staging branch to avoid conflicts
      - name: Pull latest changes from staging
        run: |
          git fetch origin
          git checkout staging || git checkout -b staging
          git pull origin staging

      # Merge changes from main into staging
      - name: Merge main into staging
        run: git merge main --no-edit

      # Push changes to staging branch
      - name: Push to staging branch
        run: git push origin staging